"use strict";
exports.__esModule = true;
var NumbersCollection_1 = require("./NumbersCollection");
var CharCollection_1 = require("./CharCollection");
var LinkedList_1 = require("./LinkedList");
var charCollection = new CharCollection_1.CharCollection("EbJuLcHeSAbCvlM");
var numbersCollection = new NumbersCollection_1.NumbersCollection([100, 55, 470, -3, 0, 88]);
var linkedList = new LinkedList_1.LinkedList();
linkedList.add(1000);
linkedList.add(0);
linkedList.add(53);
linkedList.add(7777);
linkedList.add(-654);
charCollection.sort();
linkedList.sort();
numbersCollection.sort();
console.log(numbersCollection.data);
console.log(charCollection.data);
linkedList.print();
